### ISSUE TITLE
Documentation: What Next?

### ISSUE THREAD

**Issue by tanepiper** [curiouschip/pip#7]
Hey, love the device form factor and controllers.

I followed the documentation to https://www.thisispip.com/get-started but it's empty!  I also don't see any docs for the Pip touch.

I followed the instructions here: https://learn.thisispip.com/guides/pip-hardware-preview/

* Should advise the user to check they don't put a space in the `=` part of the WiFi config

Apart from the basic config and tests is there anything to get started with?

**Comment by jaz303** [comment]
The `/get-started` will eventually host the official getting started guide that covers Pip custom UI etc. But it makes sense to point it to the preview docs for now so I've added a redirect.

Pip touch docs will be coming this week, along with RetroPie too.

The next release (`1.0.2`) will be primarily bug fixes based on feedback received so far. `1.1.0` will include a web-accessible UI and a runner for games made with Lua Löve. I expect this to be 2-3 weeks away as there's a bunch of new UI design still to integrate.
