### ISSUE TITLE
evtest Not Installed

### ISSUE THREAD

**Issue by tanepiper** [curiouschip/pip#9]
When trying the commands for the first time from the help page, `evtest` was not installed.

I installed it manually via `apt-get`

**Comment by sukhvirdhillon** [comment]
Hi Tane,

Glad to hear you got your Pip. Your delivery was the most worrisome as it had been stuck in customs for a week.

Appreciate your feedback. Can you please join our Discord Channel and Jason can help you out with any issues there? https://discord.gg/UPfKCERw <https://discord.gg/UPfKCERw>

Best regards,

Sukhvir

**Comment by jaz303** [comment]
Docs updated!
